modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="cardcapturemob"
version="1.0.0"
displayName="CardCaptureMob"
authors="Aylel"
description='''
Mod de capture pour Minecraft 1.20.1.
'''

[[dependencies.cardcapturemob]]
modId="forge"
mandatory=true
versionRange="[47.2.17,)"
ordering="NONE"
side="BOTH"

[[dependencies.cardcapturemob]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"










